chain:
    bech32_prefix: spike
    modules: []
node:
    type: remote
    config:
        rpc:
            client_name: juno
            address: http://centos.dag.fan:26657
            max_connections: 20
        grpc:
            address: centos.dag.fan:9090
            insecure: true
parsing:
    workers: 1
    listen_new_blocks: true
    parse_old_blocks: true
    parse_genesis: true
    start_height: 1
    average_block_time: 5s
database:
    name: postgres
    host: 192.168.20.2
    port: 5432
    user: postgres
    password: postgrespassword
    schema: public
    max_open_connections: 10
    max_idle_connections: 5
    partition_size: 100000
    partition_batch: 1000
logging:
    level: debug
    format: text
actions:
    host: 0.0.0.0
    port: 3000